# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON /home/ms0503/STMProjects/2023-kosen/main

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32F303xE>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_FULL_LL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:HSE_VALUE=8000000>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:HSE_STARTUP_TIMEOUT=100>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:LSE_STARTUP_TIMEOUT=5000>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:LSE_VALUE=32768>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:EXTERNAL_CLOCK_VALUE=8000000>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:HSI_VALUE=8000000>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:LSI_VALUE=40000>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:VDD_VALUE=3300>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:PREFETCH_ENABLE=1>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32F303xE>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_FULL_LL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:HSE_VALUE=8000000>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:HSE_STARTUP_TIMEOUT=100>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:LSE_STARTUP_TIMEOUT=5000>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:LSE_VALUE=32768>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:EXTERNAL_CLOCK_VALUE=8000000>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:HSI_VALUE=8000000>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:LSI_VALUE=40000>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:VDD_VALUE=3300>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:PREFETCH_ENABLE=1>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/STM32F3xx_HAL_Driver/Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/CMSIS/Device/ST/STM32F3xx/Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/CMSIS/Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/STM32F3xx_HAL_Driver/Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/CMSIS/Device/ST/STM32F3xx/Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/CMSIS/Include>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32F303ZDTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32F303ZDTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "Core/Src/Arm.cc"
    "Core/Src/ComRecv.cc"
    "Core/Src/ComSend.cc"
    "Core/Src/gpio.c"
    "Core/Src/main.cc"
    "Core/Src/RemoteEncoder.cc"
    "Core/Src/stm32f3xx_it.cc"
    "Core/Src/syscalls.c"
    "Core/Src/sysmem.c"
    "Core/Src/system_stm32f3xx.c"
    "Core/Src/tim.c"
    "Core/Src/UpDown.cc"
    "Core/Src/usart.c"
    "Core/Startup/startup_stm32f303zdtx.s"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_dma.c"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_exti.c"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_gpio.c"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_rcc.c"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_tim.c"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_usart.c"
    "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_utils.c"
    "cmake-build-debug/CMakeFiles/3.27.6/CompilerIdC/CMakeCCompilerId.c"
    "cmake-build-debug/CMakeFiles/3.27.6/CompilerIdCXX/CMakeCXXCompilerId.cpp"
    "cmake-build-minsizerel/CMakeFiles/3.27.6/CompilerIdC/CMakeCCompilerId.c"
    "cmake-build-minsizerel/CMakeFiles/3.27.6/CompilerIdCXX/CMakeCXXCompilerId.cpp"
    "cmake-build-release/CMakeFiles/3.27.6/CompilerIdC/CMakeCCompilerId.c"
    "cmake-build-release/CMakeFiles/3.27.6/CompilerIdCXX/CMakeCXXCompilerId.cpp"
    "cmake-build-relwithdebinfo/CMakeFiles/3.28.0-rc1/CompilerIdC/CMakeCCompilerId.c"
    "cmake-build-relwithdebinfo/CMakeFiles/3.28.0-rc1/CompilerIdCXX/CMakeCXXCompilerId.cpp"
    "libmecha/src/Controller.cc"
    "libmecha/src/LED.cc"
    "libmecha/src/LowLayer/Can.cc"
    "libmecha/src/LowLayer/Encoder.cc"
    "libmecha/src/LowLayer/GPIO.cc"
    "libmecha/src/MathHelper.cc"
    "libmecha/src/MiddleLayer/CytronMotorDriver.cc"
    "libmecha/src/MiddleLayer/KitanoMotorDriver.cc"
    "libmecha/src/MiddleLayer/SBDBT.cc"
    "libmecha/src/Steering/CrawlerSteering.cc"
    "libmecha/src/Steering/QuadOmniSteering.cc"
    "libmecha/tools/node/Darwin-arm64/lib/node_modules/npm/node_modules/node-gyp/gyp/data/win/large-pdb-shim.cc"
    "libmecha/tools/node/Darwin-arm64/lib/node_modules/npm/node_modules/node-gyp/src/win_delay_load_hook.cc"
    "libmecha/tools/node/Darwin-x86_64/lib/node_modules/npm/node_modules/node-gyp/gyp/data/win/large-pdb-shim.cc"
    "libmecha/tools/node/Darwin-x86_64/lib/node_modules/npm/node_modules/node-gyp/src/win_delay_load_hook.cc"
    "libmecha/tools/node/Linux-x86_64/lib/node_modules/npm/node_modules/node-gyp/gyp/data/win/large-pdb-shim.cc"
    "libmecha/tools/node/Linux-x86_64/lib/node_modules/npm/node_modules/node-gyp/src/win_delay_load_hook.cc"
    "libmecha/tools/node/Windows-x86_64/node_modules/npm/node_modules/node-gyp/gyp/data/win/large-pdb-shim.cc"
    "libmecha/tools/node/Windows-x86_64/node_modules/npm/node_modules/node-gyp/src/win_delay_load_hook.cc"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()